<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Новости");

$APPLICATION->IncludeComponent(
	"bitrix:news",
	"ourWorks",
	[
		"IBLOCK_TYPE"                     => "content",
		"IBLOCK_ID"                       => "12",
		"NEWS_COUNT"                      => "12",
		"USE_SEARCH"                      => "N",
		"USE_RSS"                         => "N",
		"USE_RATING"                      => "N",
		"USE_CATEGORIES"                  => "N",
		"USE_REVIEW"                      => "N",
		"USE_FILTER"                      => "N",
		"SORT_BY1"                        => "SORT",
		"SORT_ORDER1"                     => "ASC",
		"SORT_BY2"                        => "ID",
		"SORT_ORDER2"                     => "ASC",
		"CHECK_DATES"                     => "Y",
		"SEF_MODE"                        => "Y",
		"AJAX_MODE"                       => "N",
		"AJAX_OPTION_JUMP"                => "N",
		"AJAX_OPTION_STYLE"               => "Y",
		"AJAX_OPTION_HISTORY"             => "N",
		"AJAX_OPTION_ADDITIONAL"          => "",
		"CACHE_TYPE"                      => "A",
		"CACHE_TIME"                      => "36000000",
		"CACHE_FILTER"                    => "N",
		"CACHE_GROUPS"                    => "Y",
		"SET_LAST_MODIFIED"               => "N",
		"SET_TITLE"                       => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN"       => "N",
		"ADD_SECTIONS_CHAIN"              => "N",
		"ADD_ELEMENT_CHAIN"               => "Y",
		"USE_PERMISSIONS"                 => "N",
		"STRICT_SECTION_CHECK"            => "N",
		"COMPOSITE_FRAME_MODE"            => "A",
		"COMPOSITE_FRAME_TYPE"            => "AUTO",
		"PREVIEW_TRUNCATE_LEN"            => "",
		"LIST_ACTIVE_DATE_FORMAT"         => "d.m.Y",
		"LIST_FIELD_CODE"                 => [
			0 => "",
			1 => "",
		],
		"LIST_PROPERTY_CODE"              => [
			0 => "",
			1 => "",
		],
		"HIDE_LINK_WHEN_NO_DETAIL"        => "N",
		"DISPLAY_NAME"                    => "Y",
		"META_KEYWORDS"                   => "-",
		"META_DESCRIPTION"                => "-",
		"BROWSER_TITLE"                   => "-",
		"DETAIL_SET_CANONICAL_URL"        => "N",
		"DETAIL_ACTIVE_DATE_FORMAT"       => "d.m.Y",
		"DETAIL_FIELD_CODE"               => [
			0 => "",
			1 => "",
		],
		"DETAIL_PROPERTY_CODE"            => [
			0 => "",
			1 => "IMAGES",
			2 => "CHARACT",
			3 => "",
		],
		"DETAIL_DISPLAY_TOP_PAGER"        => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER"     => "Y",
		"DETAIL_PAGER_TITLE"              => "Страница",
		"DETAIL_PAGER_TEMPLATE"           => "",
		"DETAIL_PAGER_SHOW_ALL"           => "Y",
		"PAGER_TEMPLATE"                  => ".default",
		"DISPLAY_TOP_PAGER"               => "N",
		"DISPLAY_BOTTOM_PAGER"            => "Y",
		"PAGER_TITLE"                     => "Новости",
		"PAGER_SHOW_ALWAYS"               => "N",
		"PAGER_DESC_NUMBERING"            => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL"                  => "N",
		"PAGER_BASE_LINK_ENABLE"          => "N",
		"SET_STATUS_404"                  => "Y",
		"SHOW_404"                        => "Y",
		"MESSAGE_404"                     => "",
		"SEF_FOLDER"                      => "/news/",
		"COMPONENT_TEMPLATE"              => "ourWorks",
		"FILE_404"                        => "",
		"SEF_URL_TEMPLATES"               => [
			"news"    => "",
			"section" => "",
			"detail"  => "#ELEMENT_CODE#/",
		]
	],
	false
);
?>

<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>